name: Disguise
author: Sean_M
version: "1.0.0"
api: [1.0.0]
description: Disguise yourself as a random name.
main: Sean_M\Disguise\Main

commands:
    disguise:
        description: "Disguise yourself as a random name."
        usage: "/disguise"
        permission: disguise.command
